secretGenerator:
- name: mysql-root
  namespace: brizzom
  literals:
  - password=brizzomRoot2022@
- name: mysql-user
  namespace: brizzom
  literals:
  - username=brizzomUser
- name: mysql-user-password
  namespace: brizzom
  literals:
  - passworduser=brizzom2022@
- name: mysql-database
  namespace: brizzom
  literals:
  - database=db_brizzom