apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  namespace: brizzom
spec:
  storageClassName: do-block-storage
  capacity: 
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/www/html"